service: events

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  region: us-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "kinesis:*"
      Resource:
        - ${self:custom.events_stream}
        - ${self:custom.errors_stream}

plugins:
  - serverless-plugin-optimize

package:
  individually: true

custom:
  events_stream: "arn:aws:kinesis:us-west-1:341339899620:stream/goldstar-${opt:stage}-events"
  errors_stream: "arn:aws:kinesis:us-west-1:341339899620:stream/goldstar-${opt:stage}-events-errors"
  browserify:
    presets:
      - es2016

functions:
  processEvent:
    handler: handler.processEvent
    environment:
      errors_stream: ${self:custom.errors_stream}
    events:
      - stream:
          arn: ${self:custom.events_stream}
